// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ZIM1qkrfQVgSDFqo17EEJIMzbOdogNo',
    appId: '1:206930114075:web:381639aae39761e746eabe',
    messagingSenderId: '206930114075',
    projectId: 'oshikatsu-dev-8bb0d',
    authDomain: 'oshikatsu-dev-8bb0d.firebaseapp.com',
    databaseURL: 'https://oshikatsu-dev-8bb0d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oshikatsu-dev-8bb0d.appspot.com',
    measurementId: 'G-G8J4F1BL86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6YJErF9qj-iH8oYQuVr0RpYMGEVf-LFY',
    appId: '1:206930114075:android:5824cb5bb287963d46eabe',
    messagingSenderId: '206930114075',
    projectId: 'oshikatsu-dev-8bb0d',
    databaseURL: 'https://oshikatsu-dev-8bb0d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oshikatsu-dev-8bb0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr1UmWFcrYi00RdYgk-8XGytrLcOUVl9c',
    appId: '1:206930114075:ios:6b714f235f590fb646eabe',
    messagingSenderId: '206930114075',
    projectId: 'oshikatsu-dev-8bb0d',
    databaseURL: 'https://oshikatsu-dev-8bb0d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oshikatsu-dev-8bb0d.appspot.com',
    iosBundleId: 'com.example.oshikatsuProduct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr1UmWFcrYi00RdYgk-8XGytrLcOUVl9c',
    appId: '1:206930114075:ios:04fda9f27b13426a46eabe',
    messagingSenderId: '206930114075',
    projectId: 'oshikatsu-dev-8bb0d',
    databaseURL: 'https://oshikatsu-dev-8bb0d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'oshikatsu-dev-8bb0d.appspot.com',
    iosBundleId: 'com.example.oshikatsuProduct.RunnerTests',
  );
}
