const PROJECT_IMAGE_STORAGE = "PROJECT_IMAGE_STORAGE";
const CHAT_FILE_STORAGE = "CHAT_FILE_STORAGE";
const USER_ICON_IMAGE = "USER_ICON_IMAGE";

const ROOM_TABLE_COLLECTION_NAME = "rooms";
const USERS_TABLE_COLLECTION_NAME = "users";
const ROOM_USERS_TABLE_COLLECTION_NAME = "room_users";
const PROJECTS_TABLE_COLLECTION_NAME = "projects";